export const SET_LOADING = "app/SET_LOADING";
export const FETCH_ARTIST = "app/FETCH_ARTIST";
export const FETCH_ARTIST_SUCCESS = "app/FETCH_ARTIST_SUCCESS";
export const FETCH_ARTIST_EVENTS = "app/FETCH_ARTIST_EVENTS";
export const FETCH_ARTIST_EVENTS_SUCCESS = "app/FETCH_ARTIST_EVENTS_SUCCESS";
export const THROW_API_ERROR = "app/THROW_API_ERROR";
